#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               35 
spacebar -m config title                off 
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        30
spacebar -m config spacing_left         35
spacebar -m config spacing_right        35
spacebar -m config text_font            "Inconsolata:Regular:18.0"
spacebar -m config icon_font            "Hack Nerd Font:Bold:20.0"
spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffd3d3d3
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip                    ﱘ 
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%A %e %b %R"
spacebar -m config right_shell          off
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "$HOME/.config/cpu.sh"
spacebar -m config display main 
echo "spacebar configuration loaded.."

