#!/usr/bin/sh

sxhkd &

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-2 -d 10 

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a * desktop=^10
bspc rule -a firefox desktop=1
bspc rule -a Sublime_text desktop=2
bspc rule -a Spotify desktop=9

bspc config pointer_modifier alt
bspc config pointer_action1 move

xrandr --output DP-2 --left-of DP-4
feh --bg-fill ~/Pictures/wallpapers/bear.jpeg

$HOME/.config/polybar/launch.sh &
